name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature do you want?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Why is this useful?
    validations:
      required: true
